<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateVersionFile>true</GenerateVersionFile>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <!-- Analyzers & Versioning -->
  <ItemGroup>
    <PackageReference Include="SimpleBranchVersioning" PrivateAssets="all" />
    <PackageReference Include="Meziantou.Analyzer" PrivateAssets="all" />
    <PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" PrivateAssets="all" />
    <PackageReference Include="AsyncFixer" PrivateAssets="all" />
  </ItemGroup>

</Project>
