<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Runtime dependencies -->
  <ItemGroup>
    <PackageVersion Include="Imposter" Version="0.1.9" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="TUnit" Version="1.65.0" />
  </ItemGroup>
  <!-- Build-time only dependencies -->
  <ItemGroup>
    <PackageVersion Include="SimpleBranchVersioning" Version="0.6.1" />
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.157" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.32.0.713" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.16.0" />
    <PackageVersion Include="AsyncFixer" Version="2.1.0" />
  </ItemGroup>
</Project>