<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Runtime dependencies -->
  <ItemGroup>
    <PackageVersion Include="Imposter" Version="0.1.4" />
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.1.0" />
    <PackageVersion Include="TUnit" Version="1.9.64" />
  </ItemGroup>
  <!-- Build-time only dependencies -->
  <ItemGroup>
    <PackageVersion Include="SimpleBranchVersioning" Version="0.6.1" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.275" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.18.0.131500" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageVersion Include="AsyncFixer" Version="2.1.0" />
  </ItemGroup>
</Project>