<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Runtime dependencies -->
  <ItemGroup>
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.1" />
  </ItemGroup>

  <!-- Build-time only dependencies -->
  <ItemGroup>
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.182" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.4.0.108396" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.12.10" />
    <PackageVersion Include="AsyncFixer" Version="1.6.0" />
  </ItemGroup>

</Project>
